// Generated by gencpp from file freenove_base/adc_msg.msg
// DO NOT EDIT!


#ifndef FREENOVE_BASE_MESSAGE_ADC_MSG_H
#define FREENOVE_BASE_MESSAGE_ADC_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace freenove_base
{
template <class ContainerAllocator>
struct adc_msg_
{
  typedef adc_msg_<ContainerAllocator> Type;

  adc_msg_()
    : left(0.0)
    , right(0.0)
    , power(0.0)  {
    }
  adc_msg_(const ContainerAllocator& _alloc)
    : left(0.0)
    , right(0.0)
    , power(0.0)  {
  (void)_alloc;
    }



   typedef float _left_type;
  _left_type left;

   typedef float _right_type;
  _right_type right;

   typedef float _power_type;
  _power_type power;





  typedef boost::shared_ptr< ::freenove_base::adc_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::freenove_base::adc_msg_<ContainerAllocator> const> ConstPtr;

}; // struct adc_msg_

typedef ::freenove_base::adc_msg_<std::allocator<void> > adc_msg;

typedef boost::shared_ptr< ::freenove_base::adc_msg > adc_msgPtr;
typedef boost::shared_ptr< ::freenove_base::adc_msg const> adc_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::freenove_base::adc_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::freenove_base::adc_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::freenove_base::adc_msg_<ContainerAllocator1> & lhs, const ::freenove_base::adc_msg_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right &&
    lhs.power == rhs.power;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::freenove_base::adc_msg_<ContainerAllocator1> & lhs, const ::freenove_base::adc_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace freenove_base

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::freenove_base::adc_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::freenove_base::adc_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::freenove_base::adc_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::freenove_base::adc_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::freenove_base::adc_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::freenove_base::adc_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::freenove_base::adc_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87fdce4da0e9737b84d40aaf1c65c019";
  }

  static const char* value(const ::freenove_base::adc_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87fdce4da0e9737bULL;
  static const uint64_t static_value2 = 0x84d40aaf1c65c019ULL;
};

template<class ContainerAllocator>
struct DataType< ::freenove_base::adc_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "freenove_base/adc_msg";
  }

  static const char* value(const ::freenove_base::adc_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::freenove_base::adc_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left\n"
"float32 right\n"
"float32 power\n"
;
  }

  static const char* value(const ::freenove_base::adc_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::freenove_base::adc_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct adc_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::freenove_base::adc_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::freenove_base::adc_msg_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
    s << indent << "power: ";
    Printer<float>::stream(s, indent + "  ", v.power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FREENOVE_BASE_MESSAGE_ADC_MSG_H
