// Generated by gencpp from file freenove_base/buzzer_msg.msg
// DO NOT EDIT!


#ifndef FREENOVE_BASE_MESSAGE_BUZZER_MSG_H
#define FREENOVE_BASE_MESSAGE_BUZZER_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace freenove_base
{
template <class ContainerAllocator>
struct buzzer_msg_
{
  typedef buzzer_msg_<ContainerAllocator> Type;

  buzzer_msg_()
    : command(false)  {
    }
  buzzer_msg_(const ContainerAllocator& _alloc)
    : command(false)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::freenove_base::buzzer_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::freenove_base::buzzer_msg_<ContainerAllocator> const> ConstPtr;

}; // struct buzzer_msg_

typedef ::freenove_base::buzzer_msg_<std::allocator<void> > buzzer_msg;

typedef boost::shared_ptr< ::freenove_base::buzzer_msg > buzzer_msgPtr;
typedef boost::shared_ptr< ::freenove_base::buzzer_msg const> buzzer_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::freenove_base::buzzer_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::freenove_base::buzzer_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::freenove_base::buzzer_msg_<ContainerAllocator1> & lhs, const ::freenove_base::buzzer_msg_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::freenove_base::buzzer_msg_<ContainerAllocator1> & lhs, const ::freenove_base::buzzer_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace freenove_base

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::freenove_base::buzzer_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::freenove_base::buzzer_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::freenove_base::buzzer_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::freenove_base::buzzer_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::freenove_base::buzzer_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::freenove_base::buzzer_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::freenove_base::buzzer_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01134d7a2df15c0112a6a1d7df9d666d";
  }

  static const char* value(const ::freenove_base::buzzer_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01134d7a2df15c01ULL;
  static const uint64_t static_value2 = 0x12a6a1d7df9d666dULL;
};

template<class ContainerAllocator>
struct DataType< ::freenove_base::buzzer_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "freenove_base/buzzer_msg";
  }

  static const char* value(const ::freenove_base::buzzer_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::freenove_base::buzzer_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool command\n"
;
  }

  static const char* value(const ::freenove_base::buzzer_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::freenove_base::buzzer_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct buzzer_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::freenove_base::buzzer_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::freenove_base::buzzer_msg_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FREENOVE_BASE_MESSAGE_BUZZER_MSG_H
