// Generated by gencpp from file freenove_base/line_tracking_msg.msg
// DO NOT EDIT!


#ifndef FREENOVE_BASE_MESSAGE_LINE_TRACKING_MSG_H
#define FREENOVE_BASE_MESSAGE_LINE_TRACKING_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace freenove_base
{
template <class ContainerAllocator>
struct line_tracking_msg_
{
  typedef line_tracking_msg_<ContainerAllocator> Type;

  line_tracking_msg_()
    : left(false)
    , right(false)
    , mid(false)  {
    }
  line_tracking_msg_(const ContainerAllocator& _alloc)
    : left(false)
    , right(false)
    , mid(false)  {
  (void)_alloc;
    }



   typedef uint8_t _left_type;
  _left_type left;

   typedef uint8_t _right_type;
  _right_type right;

   typedef uint8_t _mid_type;
  _mid_type mid;





  typedef boost::shared_ptr< ::freenove_base::line_tracking_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::freenove_base::line_tracking_msg_<ContainerAllocator> const> ConstPtr;

}; // struct line_tracking_msg_

typedef ::freenove_base::line_tracking_msg_<std::allocator<void> > line_tracking_msg;

typedef boost::shared_ptr< ::freenove_base::line_tracking_msg > line_tracking_msgPtr;
typedef boost::shared_ptr< ::freenove_base::line_tracking_msg const> line_tracking_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::freenove_base::line_tracking_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::freenove_base::line_tracking_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::freenove_base::line_tracking_msg_<ContainerAllocator1> & lhs, const ::freenove_base::line_tracking_msg_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right &&
    lhs.mid == rhs.mid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::freenove_base::line_tracking_msg_<ContainerAllocator1> & lhs, const ::freenove_base::line_tracking_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace freenove_base

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::freenove_base::line_tracking_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::freenove_base::line_tracking_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::freenove_base::line_tracking_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::freenove_base::line_tracking_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::freenove_base::line_tracking_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::freenove_base::line_tracking_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::freenove_base::line_tracking_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8464e379cfd80108cb0e774a6e6ad425";
  }

  static const char* value(const ::freenove_base::line_tracking_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8464e379cfd80108ULL;
  static const uint64_t static_value2 = 0xcb0e774a6e6ad425ULL;
};

template<class ContainerAllocator>
struct DataType< ::freenove_base::line_tracking_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "freenove_base/line_tracking_msg";
  }

  static const char* value(const ::freenove_base::line_tracking_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::freenove_base::line_tracking_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool left\n"
"bool right\n"
"bool mid\n"
;
  }

  static const char* value(const ::freenove_base::line_tracking_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::freenove_base::line_tracking_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.mid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct line_tracking_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::freenove_base::line_tracking_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::freenove_base::line_tracking_msg_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right);
    s << indent << "mid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FREENOVE_BASE_MESSAGE_LINE_TRACKING_MSG_H
