// Generated by gencpp from file freenove_base/ultrasonic_srv.msg
// DO NOT EDIT!


#ifndef FREENOVE_BASE_MESSAGE_ULTRASONIC_SRV_H
#define FREENOVE_BASE_MESSAGE_ULTRASONIC_SRV_H

#include <ros/service_traits.h>


#include <freenove_base/ultrasonic_srvRequest.h>
#include <freenove_base/ultrasonic_srvResponse.h>


namespace freenove_base
{

struct ultrasonic_srv
{

typedef ultrasonic_srvRequest Request;
typedef ultrasonic_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ultrasonic_srv
} // namespace freenove_base


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::freenove_base::ultrasonic_srv > {
  static const char* value()
  {
    return "f243fa36d849f4a9e106af7b84e04939";
  }

  static const char* value(const ::freenove_base::ultrasonic_srv&) { return value(); }
};

template<>
struct DataType< ::freenove_base::ultrasonic_srv > {
  static const char* value()
  {
    return "freenove_base/ultrasonic_srv";
  }

  static const char* value(const ::freenove_base::ultrasonic_srv&) { return value(); }
};


// service_traits::MD5Sum< ::freenove_base::ultrasonic_srvRequest> should match
// service_traits::MD5Sum< ::freenove_base::ultrasonic_srv >
template<>
struct MD5Sum< ::freenove_base::ultrasonic_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::freenove_base::ultrasonic_srv >::value();
  }
  static const char* value(const ::freenove_base::ultrasonic_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::freenove_base::ultrasonic_srvRequest> should match
// service_traits::DataType< ::freenove_base::ultrasonic_srv >
template<>
struct DataType< ::freenove_base::ultrasonic_srvRequest>
{
  static const char* value()
  {
    return DataType< ::freenove_base::ultrasonic_srv >::value();
  }
  static const char* value(const ::freenove_base::ultrasonic_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::freenove_base::ultrasonic_srvResponse> should match
// service_traits::MD5Sum< ::freenove_base::ultrasonic_srv >
template<>
struct MD5Sum< ::freenove_base::ultrasonic_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::freenove_base::ultrasonic_srv >::value();
  }
  static const char* value(const ::freenove_base::ultrasonic_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::freenove_base::ultrasonic_srvResponse> should match
// service_traits::DataType< ::freenove_base::ultrasonic_srv >
template<>
struct DataType< ::freenove_base::ultrasonic_srvResponse>
{
  static const char* value()
  {
    return DataType< ::freenove_base::ultrasonic_srv >::value();
  }
  static const char* value(const ::freenove_base::ultrasonic_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FREENOVE_BASE_MESSAGE_ULTRASONIC_SRV_H
